version: '3.3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - database
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - database
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - database
    restart: always
  ftp :
    container_name: ftp
    build:
      context: ./requirements/bonus/FTP
    env_file:
      - .env
    volumes:
      - wordpress:/home/${FTP_USER}/wordpress
    ports:
      - "21:21"
      - "21000-21100:21000-21100"
    depends_on:
      - wordpress
    restart : on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /Users/alaassir/Desktop/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /Users/alaassir/Desktop/data/mariadb
      o: bind

networks:
  database: