version: '3.3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - database
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    networks:
      - database
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - database
    restart: always

networks:
  database: