global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8081']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
